# Generated by Django 3.1.7 on 2021-02-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveration',
            old_name='resveration',
            new_name='reservation_location',
        ),
    ]
